pub mod cli;
pub mod commit;
pub mod diff;
pub mod flow;
pub mod log;
pub mod patch;
pub mod operation;
pub mod refs;
pub mod status;
pub mod submodule;
pub mod worktree;

pub use cli::Git;
pub use commit::CommitDetail;
pub use diff::{file_diff, DiffOptions, DiffTarget, FileDiff};
pub use flow::{FinishOptions, FlowConfig, FlowKind, FlowStatus};
pub use log::{log, LogPage};
pub use operation::RepoState;
pub use refs::{refs, RefsSnapshot};
pub use status::{status, RepoStatus};
pub use submodule::Submodule;
pub use worktree::Worktree;
